services:
  - type: web
    name: dailyowo-web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: dailyowo-web
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production